name: Release a new version

on:
    push:
      tags:
        - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Create Release
          id: create_release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{ github.ref_name }}
            name: Release ${{ github.ref_name }}
            draft: false
            prerelease: false
            generate_release_notes: true
