name: 'Terraform TFLint'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tflint:
    name: 'TFLint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          github_token: ${{ secrets.github_token }}
      
      - name: Run TFLint
        run: tflint -f compact --recursive           
