name: 'Terraform Lint'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tflint:
    name: 'TFLint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1

      - name: 'TFLint'
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review