name: 'tfsec'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tfsec:
    name: 'tfsec'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'tfsec'
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
            tfsec_formats: 'checkstyle'
            github_token: ${{ github.token }}

      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'checkstyle-result.xml'
