name: 'tfsec'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tfsec:
    name: 'tfsec'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'tfsec'
        uses: triat/terraform-security-scan@v3.1.0
        with:
            tfsec_output_format: 'checkstyle'
            tfsec_output_file: checkstyle-result.xml

      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'checkstyle-result.xml'
