name: 'Terraform Lint'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tflint:
    name: 'TFLint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      
      - name: Run Tfsec
        uses: aquasecurity/tfsec-action@v1.0.0         
